global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: "slack-notifications"
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
  - receiver: "slack-notifications"

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alertmanager_input_error'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}
