- job_name: 'snmp_unifi'
  scrape_interval: 30s
  scrape_timeout: 29s
  static_configs:
    - targets: ['172.16.0.1']  # SNMP device.
  metrics_path: /snmp
  params:
    module: [if_mib]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter.snmp-exporter.svc.cluster.local:9116  # The SNMP exporter's real hostname:port.